### ISSUE TITLE
Suggestion to add the requirement not included!

### ISSUE THREAD

**Issue by firemanxbr** [Azure/azure-docs-cli-python#1106]
$ sudo apt-get install lsb-release curl -y

NOTE: before step "1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* Content: [Install the Azure CLI on Linux with apt](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli-apt.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-apt.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@firemanxbr - I'm not sure if `lsb_release` is even available on all Debian-derived distributions, which is why installing the package was left out. But it's definitely an issue that installation is only suggested in troubleshooting. I'll do some investigation and see if the instructions can be improved.

**Comment by firemanxbr** [comment]
@sptramer I'm using Windows Subsystem Linux with Debian Stretch installed. I believe have other users following the same way to use Linux on Windows [1]. Another alternative to adding the Azure CLI repository could be: 

Steps to install Azure CLI to Debian 8 (jessie)
$ sudo apt-add-repository 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ jessie main' --keyserver=https://packages.microsoft.com/keys/microsoft.asc --update
$ sudo apt-get install apt-transport-https azure-cli

Steps to install Azure CLI to Debian 9 (stretch)
$ sudo apt-get install software-properties-common -y
$ sudo apt-add-repository 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ stretch main' --keyserver=https://packages.microsoft.com/keys/microsoft.asc --update
$ sudo apt-get install apt-transport-https azure-cli

With these steps, we can reduce the dependency of "curl" and "lsb-realease" packages. 

[1]: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by sptramer** [comment]
@firemanxbr The `lsb-release` dependency is so that the Debian/Ubuntu distribution name can be correctly detected without having to have separate install instructions for all of our supported and tested platforms (currently 6) as well as providing support for derived distributions. The removal of the `curl` dependency is welcome though.
