### ISSUE TITLE
Try it! .. 

### ISSUE THREAD

**Issue by bhrionn** [Azure/azure-docs-cli-python#1140]
Hi, Azure is great . But Azure CLI is a bit confusing. "Try It" feature never works for me. The back slash for long azcli scripts require re formatting ( i.e. remove the  '\' and put on one line to run the command and cannot run multiple azcli commands seemlessly from Windows. Are all these features ?? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc5a121-5a89-6c37-6ccd-afe396046882
* Version Independent ID: bda58565-6191-a991-9646-e5b9bd58896a
* Content: [Create virtual machines with the Azure CLI](https://docs.microsoft.com/en-ie/cli/azure/azure-cli-vm-tutorial?tutorial-step=8&view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/azure-cli-vm-tutorial.yml](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/azure-cli-vm-tutorial.yml)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
As the CLI overview page now states, all examples on docs (unless otherwise specified) are written for the Linux `bash` shell, since that is the primary audience for the CLI. The same is true of any examples contained in the CLI `-h` help. For now you will need to edit scripts to have them run under PowerShell.

You are welcome to make a feature request to the engineering team to add paltform-sensitive examples: https://github.com/azure/azure-cli/issues

**Comment by abhishek1319** [comment]
I have tried hard in the Setting environment variable part. However, I am not sure how to do it? This does not explains the out of it. I tried running az vm show --name .... --resource-group .... --query 'networkProfile.network.Interfaces[].id' --output tsv

Its just does not give any output at all. And prints the networkProfile.network.Interfaces[].id as is. Please suggest.
