### ISSUE TITLE
Linux script shouldn't be used?

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-docs-cli-python#1161]
In discussing with others, the installation script for Linux here (using curl/bash) shouldn't be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7895b9a-9a6a-cd98-6947-0e4a26eda9a3
* Version Independent ID: a3f27295-3e2e-a36d-02c2-8897295fc443
* Content: [Install the Azure CLI for Linux manually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest#install-or-update)
* Content Source: [docs-ref-conceptual/install-azure-cli-linux.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli-linux.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by timheuer** [comment]
@yugangw-msft

**Comment by yugangw-msft** [comment]
Apologize if I have communicated out the some wrong thing, so rephrase here
1. Please do use bundle installer if is available
2. If 1 is not applicable, say on less popular distro, you can use curl script, and we can support it but due to engineering resources, we might not be able to get to it soon.

**Comment by timheuer** [comment]
Got it...thanks for clarifying the position.  It does read that way in the doc (header warning) but we are aware of a lot of people using this method when brew fails.
