### ISSUE TITLE
Instructions on Ubuntu fail: gpg: connecting dirmngr failed

### ISSUE THREAD

**Issue by MaurGi** [Azure/azure-docs-cli-python#1181]
See https://github.com/Microsoft/WSL/issues/3696

Do you have alternative steps?

**Comment by MaurGi** [comment]
This was fixed following instructions on https://github.com/Azure/azure-docs-cli-python/issues/1164

Kindly either update the doc to add the workaround or keep the issue open until the WSL isse is fixed?

**Comment by sptramer** [comment]
The issue indicates that the problem has been fixed in Windows 1809, which is no longer an insider build and has been publicly released. Please make sure you follow the WSL troubleshooting steps and update to the latest available build of Windows. If you still experience a problem, file an issue with the WSL team.
