### ISSUE TITLE
how to get azure-cli-2.0.52 (Which has bot service 0.4.3)

### ISSUE THREAD

**Issue by ashoksamal6363** [Azure/azure-docs-cli-python#1209]
how to get azure-cli-2.0.52 (Which has bot service 0.4.3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* Content: [Install the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
* Content Source: [docs-ref-conceptual/install-azure-cli.md](https://github.com/Azure/azure-docs-cli-python/blob/master/docs-ref-conceptual/install-azure-cli.md)
* Product: **azure**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by gabog** [comment]
I think you should be able to get it if you use https://azurecliprod.azureedge.net/msi/azure-cli-2.0.52.msi

**Comment by sptramer** [comment]
All older releases are available via https://github.com/Azure/azure-cli/releases. We don't officially offer older releases as an MSI. If you have a need for a specific release due to a bug that was introduced or a feature which is now missing, file a [bug report](http://github.com/azure/azure-cli/issues) with CLI engineering.
