### ISSUE TITLE
Linux instructions don't work

### ISSUE THREAD

**Issue by andrewb-ms** [Azure/azure-docs-cli-python#592]
Am getting this error:

gpg: keyserver receive failed: No dirmngr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7bd326-07b2-caaa-7155-5852fc2dfa3f
* Version Independent ID: c44d0547-d5cd-8934-00f8-79e2f4df53ac
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli.md)
* Service: multiple

**Comment by mohit14mar** [comment]
This has been assigned to content owner and we will get back to you soon.

**Comment by sptramer** [comment]
@andrewb-ms In order to resolve this issue, I need more information:

* The installation method you're trying
* Your running Linux installation
* Your installed versions of Python, PGP, OpenSSL, and libFFI

In particular there are issues with importing PGP keys under `apt` in Debian Stretch. Please see https://www.raspberrypi.org/forums/viewtopic.php?t=193536 - this is an issue beyond our control.

Our package does __not__ officially support Debian Stretch. We offer packages for Ubuntu Wheezy and Ubuntu Xenial.

**Comment by sptramer** [comment]
OpenSSL compatibility issues is being worked on by engineering. https://github.com/Azure/azure-cli/issues/3720

**Comment by andrewb-ms** [comment]
Shared the details on the above github issue.

**Comment by sptramer** [comment]
@andrewb-ms Please see https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#troubleshooting which has been updated. These instructions should resolve your `apt-key` issue. The resolution was tested on a clean install of Debian Stretch.

**Comment by sptramer** [comment]
The Linux install instructions page has been updated with troubleshooting information, and explicitly states which distributions `apt` install has been tested on.

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest
