### ISSUE TITLE
Tutorial steps for creating a Linux VM with Azure CLI 2.0 result in an error

### ISSUE THREAD

**Issue by tleonhardt** [Azure/azure-docs-cli-python#599]
I ran the command-line as instructed above to create a UbuntuLTS VM in westus2 and got an error message similar to the following:

"error": {
    "code": "SkuNotAvailable",
    "message": "The requested size for resource '/subscriptions/<big_hex_num>/resourceGroups/MyWestus2ResourceGroup/providers/Microsoft.Compute/virtualMachines/MyLinuxVM' is currently not available in location 'westus2' zones '' for subscription '< big_hex_num>'. Please try another size or deploy to a different location or zones

It would be really nice if the instructions in this "hello world" tutorial worked seamlessly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c268a98-afcb-d2c2-87c7-880d52900533
* Version Independent ID: 4c835da4-38bc-22a8-67b4-dd522adcc0e3
* [Content](https://docs.microsoft.com/en-us/cli/azure/get-started-with-azure-cli?view=azure-cli-latest)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/get-started-with-azure-cli.md)
* Service: multiple

**Comment by micahmckittrick** [comment]
Thanks for the feedback. The issue you are running into is due to your subscription not being enabled to deploy that Sku/ Size in that location. You should be able to simply modify the commands to deploy to another region that your subscription is enabled for. Else, you can always open a ticket to Subscription & Billing and request they unlock that Sku/ Size in that Region for you.
