### ISSUE TITLE
lsb_release -cs in linuxmint is sylvia - should point to base distribution instead

### ISSUE THREAD

**Issue by sahil87** [Azure/azure-docs-cli-python#648]
Upstream distribution information resides in /etc/upstream-release/lsb-release

The first line of the installation script could be modified to:

AZ_REPO=$(lsb_release -cs)
if [ -f /etc/upstream-release/lsb-release ]
then
  . /etc/upstream-release/lsb-release
  AZ_REPO=$DISTRIB_CODENAME
fi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1526a9-7f22-504e-484c-0f3edc11b178
* Version Independent ID: c5dec108-efcd-aa77-04b5-803b6b894dba
* [Content](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest#)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/docs-ref-conceptual/install-azure-cli-apt.md)
* Service: multiple

**Comment by sptramer** [comment]
Unfortunately we cannot include information for every Linux distribution in the install instructions for `apt`, due to the wide number of available Debian-based distributions (see https://en.wikipedia.org/wiki/List_of_Linux_distributions#Debian-based). Adding special-casing instructions like this causes a problem because other distributions may deviate from the requirements of Debian/Ubuntu as to where LSB information is required to be stored and how it is treated by `lsb_release` (see https://wiki.ubuntu.com/DerivativeDistroHowto#File_.2Fetc.2Flsb-release).

The officially tested and supported distributions are also included at the top of the install page. If we later decide to add Mint as a supported and tested platform, the instructions will be updated.
