### ISSUE TITLE
Installation in Mac without brew

### ISSUE THREAD

**Issue by redborian** [Azure/azure-docs-cli-python#768]
Please provide a way to install azure cli in Mac without using brew package manager.

**Comment by sptramer** [comment]
We only recommend and officially support using Homebrew on macOS, but you may also follow the installation script instructions:

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?view=azure-cli-latest

**Comment by bartmcleod** [comment]
Why is this just closed? That seems like a disputable approach for a company that wants to reach out to different kinds of developers. I do not use homebrew, I use macports, because homebrew caused me nothing but trouble. There is no way I will switch to homebrew just because it is considered mainstream.

**Comment by nani1211** [comment]
I have anaconda installed on mac. after that install azcli using pip

**Comment by beakerfm** [comment]
> I have anaconda installed on mac. after that install azcli using pip

That's good feedback and valid alternative installation option. Much better than suggesting `apt-get` instructions for Linux which don't work on Mac directly (hence `brew` as alternative but not an option for everyone). Pip is great suggestion.

**Comment by mike-pt** [comment]
My suggestion is simply provide a binary, you don't need to support the community package managers, if you want to that's a bonus, but then why brew and not macports? or package manager X? folks will just ask about their favorite one.

I personally can't use brew, because of security constrains, the regular path can not be writen to with a normal user, and honestly not requiring admin account/sudo for install/uninstall of packages feels wrong to me anyway, so I use macports, others will probably argue different, but having a pre build binary for macOS would just be easier IMHO

**Comment by rickyzhang82** [comment]
I have been using macport for years. I don't want to install homebrew to run az cli. Because it may cause any potential conflicts with my macports development stacks.

Why you make it exclusive to homebrew only? I don't get it.

**Comment by jessiepurser** [comment]
This worked for me (without anaconda):
`pip install azure-cli`

**Comment by lisbethw1130** [comment]
it's really surprising that such a big company has spent years dealing with this

**Comment by bartmcleod** [comment]
An few years ago I finally gave in and remove macports and installed homebrew. It finally worked for me and `brew install azure-cli` also worked, but I had to open a new terminal tab to be able to use the az command. So don't try to use it directly after installation in the same terminal window.

**Comment by mike-pt** [comment]
> it's really surprising that such a big company has spent years dealing with this

I mean there is a supported way and they closed it as "nope not happening" so its not taking years... its not happening, and to be honest the fact that they actually offer support themselves for on unofficial package manager (brew) is pretty great IMHO. I mean apple is pretty intense on forcing vendors to not distribute DMGs/binanries if they want to be on the app store right?

There also the pip way... and https://hub.docker.com/_/microsoft-azure-cli, which we can spin up in seconds on macOS 

That said the formula code https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb is open source, maybe someone could use it to convert to macports...

I don't use brew myself so that would be nice, I still think the binary is the way to go, cause then it doesn't create the dependency on  any of the unofficial package managers, but since the pip way or docker works I really don't see this as a big deal just a nice to have, and quite frequently understand why thy rejected it, its really not surprising at all.
